name:                wikigame
version:             0.1.0.0
github:              "benweedon/wikigame"
# license:             BSD3
author:              "Ben Weedon"
maintainer:          "ben@weedon.email"
copyright:           "2020 Ben Weedon"

# extra-source-files:
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/benweedon/wikigame#readme>

dependencies:
- base >= 4.7 && < 5
- scalpel

library:
  source-dirs: src

executables:
  wikigame-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - wikigame

tests:
  wikigame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - wikigame
